### ISSUE TITLE
Local connection decoding errors

### ISSUE THREAD

**Issue by uSpike** [philpep/testinfra#148]
```
pip (9.0.1)
pkg-resources (0.0.0)
pluggy (0.4.0)
py (1.4.31)
pytest (3.0.4)
setuptools (28.8.0)
six (1.10.0)
tox (2.4.1)
virtualenv (15.0.3)
wheel (0.30.0a0)
```

Simple reproduction:

```
import testinfra
>>> testinfra.get_backend('local://').get_module('Command').check_output('echo \xaa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testinfra/modules/base.py", line 51, in check_output
    out = self.run(command, *args, **kwargs)
  File "testinfra/modules/base.py", line 23, in run
    return self._backend.run(command, *args, **kwargs)
  File "testinfra/backend/local.py", line 33, in run
    return self.run_local(self.get_command(command, *args))
  File "testinfra/backend/base.py", line 167, in run_local
    command = self.encode(command)
  File "testinfra/backend/base.py", line 214, in encode
    return data.encode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 5: ordinal not in range(128)
>>> 
```

**Comment by uSpike** [comment]
Also should note python 2.

**Comment by uSpike** [comment]
OK, so my above example is pretty stupid, since it's failing on encoding the input command.

The real problem I'm facing is decoding output from a command.

To recreate (python 2.7.6),

test.sh contents:
```
#!/bin/bash

echo -e '\xaa'
```

```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import testinfra
>>> testinfra.get_backend('local://').get_module('Command').check_output('./test.sh')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testinfra/modules/base.py", line 55, in check_output
    if len(out.stdout) and out.stdout[-1] == "\n":
  File "testinfra/backend/base.py", line 48, in stdout
    self._stdout = self._backend.decode(self._stdout_bytes)
  File "testinfra/backend/base.py", line 210, in decode
    return data.decode(self.encoding)
  File "/tmp/tmp.G1S9dGp7ul/venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xaa in position 0: invalid start byte
>>> 
```

**Comment by philpep** [comment]
I think you're not supposed to decode stdout here because it's binary data. What about reading ``stdout_bytes`` instead ?

```
>>> testinfra.get_backend('local://').get_module('Command')(u'./test.sh').stdout_bytes
'\xaa\n'
```

**Comment by uSpike** [comment]
What if you don't expect the output to be unicode, but it is?  The issue came about when running a `systemctl` command which had some unicode in it, and `check_output` failed.

**Comment by philpep** [comment]
`\xaa` is not an utf8 character. What systemctl command did you run ?

**Comment by uSpike** [comment]
`systemctl status apache2` was the command (ubuntu 16.04 server), and I'm aware of the `Service` module as an alternative.  I don't have the full log with the specific error but it was similar, will work on that.
