### ISSUE TITLE
Install importlib as dependency for python 2.6

### ISSUE THREAD

**Issue by dbryant4** [philpep/testinfra#171]
After installing testinfra 1.5.0 in our python 2.6 (default centos 6 python) based test environment, we began to receive the following error:

```
Traceback (most recent call last):
   File "/usr/bin/testinfra", line 7, in <module>
     from testinfra.main import main
   File "/usr/lib/python2.6/site-packages/testinfra/__init__.py", line 16, in <module>
     from testinfra import backend
   File "/usr/lib/python2.6/site-packages/testinfra/backend/__init__.py", line 16, in <module>
     import importlib
 ImportError: No module named importlib
```

After installing `importlib` using `pip`, testinfra began working as expected. It would be nice to set `importlib` as a dependency so that `pip install testinfra` will automatically install `importlib`.

**Comment by philpep** [comment]
Although testinfra doesn't support python 2.6 (which is unmaintained), this has been fixed in 1.5.1.
Thanks for reporting.
