### ISSUE TITLE
testinfra conflicts with pytest-flake8

### ISSUE THREAD

**Issue by calind** [philpep/testinfra#210]
```
$ make lint
py.test -v --color=yes --flake8 -m 'flake8' -p 'no:testinfra'
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 2.7.10, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /Users/calin/.virtualenvs/ansible-playbooks/bin/python
cachedir: .cache
rootdir: /Users/calin/work/ansible-playbooks, inifile:
plugins: testinfra-1.6.3, flake8-0.8.1
collected 13 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/main.py", line 132, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/main.py", line 141, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/main.py", line 604, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/calin/.virtualenvs/ansible-playbooks/lib/python2.7/site-packages/testinfra/plugin.py", line 149, in pytest_collection_finish
INTERNALERROR>     deprecated_used |= (set(item.fixturenames) & deprecated_modules)
INTERNALERROR> AttributeError: 'Flake8Item' object has no attribute 'fixturenames'

======================================================================================================== no tests ran in 0.17 seconds ========================================================================================================
make: *** [lint] Error 3
```

**Comment by philpep** [comment]
I think this is fixed by dc212d8df019a133e55a659ad809db0681e7f2c0 (released in 1.9.1)
