### ISSUE TITLE
not working with pytest 5.0.1

### ISSUE THREAD

**Issue by Constantin07** [philpep/testinfra#461]
Hi,

I'm getting the below issue when trying to run testinfra on CentOS 7.2

```python
--> Executing Testinfra tests found in /root/test/ansible/roles/ctop/molecule/default/tests/...
Traceback (most recent call last):
  File "/usr/bin/py.test", line 11, in <module>
    load_entry_point('pytest==5.0.1', 'console_scripts', 'py.test')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 462
    def _get_assertion_exprs(src: bytes):  # -> Dict[int, str]
                                ^
SyntaxError: invalid syntax
```

```bash
# python -V
Python 2.7.5
```

```python
# python
Python 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 462
    def _get_assertion_exprs(src: bytes):  # -> Dict[int, str]
                                ^
SyntaxError: invalid syntax

```

Any idea what the issue could be ?

**Comment by philpep** [comment]
Hi,

pytest 5.0 is not compatible with python 2, see https://docs.pytest.org/en/latest/py27-py34-deprecation.html

**Comment by Constantin07** [comment]
Thanks @philpep 
Downgraded to 4.6.4 and it works.
