### ISSUE TITLE
Ansible v1 error handling

### ISSUE THREAD

**Issue by philpep** [philpep/testinfra#83]
Consider this simple test:

```python
def test_foo(Ansible):
    Ansible("debug", "msg={{ foo }}")
```

WIth ansible v1 this produce an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testinfra/modules/ansible.py", line 48, in __call__
    module_name, module_args, check=check, **kwargs)
  File "testinfra/backend/ansible.py", line 60, in run_ansible
    **kwargs)
  File "testinfra/utils/ansible_runner.py", line 199, in run
    host, module_name, module_args, **kwargs)
  File "testinfra/utils/ansible_runner.py", line 85, in run
    **kwargs).run()["contacted"][host]
KeyError: 'localhost'
```

Expected result is like ansible v2: `{'msg': u"'foo' is undefined", 'failed': True}`

**Comment by retr0h** [comment]
I am able to access variables which are defined in the file referenced by `--ansible-inventory`.  However, I am unable to reference normal ansible inventory such as anything gathered by facts or role defaults `defaults/main.yml`.

```
[jodewey:~/git/ansible-systems/roles/etc_hosts] [venv] correct-etc-hosts-test(+8/-3) 1 ± cat .molecule/ansible_inventory
etc-hosts ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/jodewey/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant
etc-hosts ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/jodewey/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant

[aio]
etc-hosts
etc-hosts
```
